CREATE VIEW user_role_view AS
SELECT u.USER_ID, u.USERNAME, u.FIRST_NAME, u.LAST_NAME, u.EMAIL, u.PHONE_NUMBER, u.ADDRESS, u.DATE_OF_BIRTH, u.ACTIVE, u.USER_IMAGE, 
       r.ROLE_NAME
FROM SB_USER u
JOIN SB_USER_ROLE ur ON u.USER_ID = ur.USER_ID
JOIN SB_ROLE r ON ur.ROLE_ID = r.ROLE_ID;