CREATE TABLE SB_ACCOUNT (
    ACCOUNT_ID      NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    NOT NULL,
    USER_ID         NUMBER                                                          NOT NULL,
    ACC_TYPE_ID     NUMBER                                                          NOT NULL,
    CURRENCY_ID     NUMBER                                                          NOT NULL,
    BALANCE         NUMBER                                                          NOT NULL,
    CREATED_DATE    DATE                DEFAULT SYSDATE                             NOT NULL,
    CREATED_BY      VARCHAR2(64)                                                    NOT NULL,
    MODIFIED_DATE   DATE                DEFAULT SYSDATE                                     ,
    MODIFIED_BY     VARCHAR2(64)                                                            ,
    PRIMARY KEY (ACCOUNT_ID)
);

ALTER TABLE SB_ACCOUNT ADD (
    CONSTRAINT USER_ACC_FK FOREIGN KEY (USER_ID) REFERENCES SB_USER(USER_ID),
    CONSTRAINT ACC_TYPE_FK FOREIGN KEY (ACC_TYPE_ID) REFERENCES SB_ACC_TYPE(ACC_TYPE_ID),
    CONSTRAINT CURRENCY_FK FOREIGN KEY (CURRENCY_ID) REFERENCES SB_CURRENCY(CURRENCY_ID)
);