CREATE TABLE SB_ROLE (
    ROLE_ID         NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    NOT NULL,
    ROLE_NAME       VARCHAR2(64)                                                    NOT NULL,
    DISCRIPTION     VARCHAR2(256)                                                           ,
    CREATED_DATE    DATE                DEFAULT SYSDATE                             NOT NULL,
    CREATED_BY      VARCHAR2(64)                                                    NOT NULL,
    MODIFIED_DATE   DATE                DEFAULT SYSDATE                                     ,
    MODIFIED_BY     VARCHAR2(64)                                                            ,
    PRIMARY KEY(ROLE_ID)
);

ALTER TABLE SB_ROLE
    ADD CONSTRAINT SB_ROLE_UK UNIQUE (ROLE_NAME)
;