CREATE TABLE SB_TRANSACTION (
    TRANSACTION_ID      NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    NOT NULL,
    SEND_ACC_ID         NUMBER                                                          NOT NULL,
    RECEIVER_ACC_ID     NUMBER                                                          NOT NULL,
    AMOUNT              NUMBER                                                          NOT NULL,
    TRANSACTION_DATE    DATE                                                            NOT NULL,
    CREATED_DATE        DATE                DEFAULT SYSDATE                             NOT NULL,
    CREATED_BY          VARCHAR2(64)                                                    NOT NULL,
    MODIFIED_DATE       DATE                DEFAULT SYSDATE                                     ,
    MODIFIED_BY         VARCHAR2(64)                                                            ,
    PRIMARY KEY (TRANSACTION_ID)
);

ALTER TABLE SB_TRANSACTION ADD (
    CONSTRAINT SENDER_ACC_FK FOREIGN KEY (SENDER_ACC_ID) REFERENCES SB_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT RECEIVER_ACC_FK FOREIGN KEY (RECEIVER_ACC_ID) REFERENCES SB_ACCOUNT(ACCOUNT_ID),
    CONSTRAINT TRANSACTION_UK UNIQUE (SEND_ACC_ID, RECEIVER_ACC_ID)
);