CREATE TABLE SB_USER (
    USER_ID         NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    NOT NULL,
    USERNAME        VARCHAR2(64)                                                    NOT NULL,
    FIRST_NAME      VARCHAR2(64)                                                    NOT NULL,
    LAST_NAME       VARCHAR2(64)                                                    NOT NULL,
    EMAIL           VARCHAR2(128)                                                   NOT NULL,
    PHONE_NUMBER    NUMBER                                                          NOT NULL,
    ADDRESS         VARCHAR2(128)                                                   NOT NULL,
    DATE_OF_BIRTH   DATE                                                            NOT NULL,
    PASSWORD        VARCHAR2(128)                                                   NOT NULL,
    ACTIVE          VARCHAR2(3)         DEFAULT 'YES'                               NOT NULL,
    USER_IMAGE      BLOB                                                            NOT NULL,
    CREATED_DATE    DATE                DEFAULT SYSDATE                             NOT NULL,
    CREATED_BY      VARCHAR2(64)                                                    NOT NULL,
    MODIFIED_DATE   DATE                DEFAULT SYSDATE                                     ,
    MODIFIED_BY     VARCHAR2(64)                                                            ,
    PRIMARY KEY (USER_ID)
);

ALTER TABLE SB_USER
    ADD CONSTRAINT SB_USER_UK UNIQUE (USERNAME, EMAIL, PHONE_NUMBER)
;