CREATE TABLE SB_USER_ROLE (
    USER_ROLE_ID    NUMBER              GENERATED BY DEFAULT ON NULL AS IDENTITY    NOT NULL,
    USER_ID         NUMBER                                                          NOT NULL,
    ROLE_ID         NUMBER                                                          NOT NULL,
    CREATED_DATE    DATE                DEFAULT SYSDATE                             NOT NULL,
    CREATED_BY      VARCHAR2(64)                                                    NOT NULL,
    MODIFIED_DATE   DATE                DEFAULT SYSDATE                                     ,
    MODIFIED_BY     VARCHAR2(64)                                                            ,
    PRIMARY KEY (USER_ROLE_ID)
);

ALTER TABLE SB_USER_ROLE ADD (
    CONSTRAINT USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES SB_USER(USER_ID),
    CONSTRAINT ROLE_ID_FK FOREIGN KEY(ROLE_ID) REFERENCES SB_ROLE(ROLE_ID),
    CONSTRAINT SB_USER_ROLE_UK UNIQUE (USER_ID, ROLE_ID)
);